@startuml

Пользователь -> Интерфейс: запуск
activate Интерфейс
activate История


Пользователь -> Интерфейс: ввод выражения
Интерфейс -> MyCalculator: проверка выражения
activate MyCalculator
MyCalculator -> Интерфейс: true
Интерфейс -> MyCalculator: вычисление выражение
MyCalculator -> Интерфейс: результат
deactivate MyCalculator

Пользователь -> Интерфейс: сохранить результат
Интерфейс -> История: сохранить результат

Пользователь -> Интерфейс: посмотреть историю
Интерфейс -> История: вызов
История -> Интерфейс: показать историю

Пользователь -> Интерфейс: закрыть

deactivate Интерфейс
deactivate История

@enduml

