@startuml
left to right direction

actor Пользователь

Пользователь -- (ввод выражения)
Пользователь -- (получить результат)
Пользователь -- (сохранить результат)
Пользователь -- (посмотреть историю)

(ввод выражения) <|-- (проверка выражения)

(проверка выражения) .> (Обработка исключений) : include
(проверка выражения) .> (Проверка на валидность) : include
(проверка выражения) <|-- (вычисление выражения)

(вычисление выражения) .> (Операции) : include

(получить результат) .> (вычисление выражения) : use

(сохранить результат) .> (получить результат) : extend

@enduml